CREATE TABLE NAP_REPORTS_DETAILS
(
    SRP_ID NUMBER NOT NULL
    , SRP_RAP_ID NUMBER NOT NULL
    , SRP_TYP VARCHAR2(20)
    , SRP_NAZWA VARCHAR2(500)
    , SRP_SQL CLOB
    , SRP_F_OUTER VARCHAR2(1)
    , SRP_FORMULA VARCHAR2(4000)
);